//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns://www.fortifysoftware.com/schema/rules")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="xmlns://www.fortifysoftware.com/schema/rules", IsNullable=false)]
public partial class RulePack {
    
    private string rulePackIDField;
    
    private string sKUField;
    
    private string nameField;
    
    private string versionField;
    
    private string descriptionField;
    
    private RulePackRules[] rulesField;
    
    /// <remarks/>
    public string RulePackID {
        get {
            return this.rulePackIDField;
        }
        set {
            this.rulePackIDField = value;
        }
    }
    
    /// <remarks/>
    public string SKU {
        get {
            return this.sKUField;
        }
        set {
            this.sKUField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Rules")]
    public RulePackRules[] Rules {
        get {
            return this.rulesField;
        }
        set {
            this.rulesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns://www.fortifysoftware.com/schema/rules")]
public partial class RulePackRules {
    
    private RulePackRulesRuleDefinitionsCustomDescriptionRule[] ruleDefinitionsField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("CustomDescriptionRule", typeof(RulePackRulesRuleDefinitionsCustomDescriptionRule), IsNullable=false)]
    public RulePackRulesRuleDefinitionsCustomDescriptionRule[] RuleDefinitions {
        get {
            return this.ruleDefinitionsField;
        }
        set {
            this.ruleDefinitionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns://www.fortifysoftware.com/schema/rules")]
public partial class RulePackRulesRuleDefinitionsCustomDescriptionRule {
    
    private string ruleIDField;
    
    private RulePackRulesRuleDefinitionsCustomDescriptionRuleRuleMatch[] ruleMatchField;
    
    private RulePackRulesRuleDefinitionsCustomDescriptionRuleDescription[] descriptionField;
    
    private string formatVersionField;
    
    /// <remarks/>
    public string RuleID {
        get {
            return this.ruleIDField;
        }
        set {
            this.ruleIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RuleMatch")]
    public RulePackRulesRuleDefinitionsCustomDescriptionRuleRuleMatch[] RuleMatch {
        get {
            return this.ruleMatchField;
        }
        set {
            this.ruleMatchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Description")]
    public RulePackRulesRuleDefinitionsCustomDescriptionRuleDescription[] Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string formatVersion {
        get {
            return this.formatVersionField;
        }
        set {
            this.formatVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns://www.fortifysoftware.com/schema/rules")]
public partial class RulePackRulesRuleDefinitionsCustomDescriptionRuleRuleMatch {
    
    private RulePackRulesRuleDefinitionsCustomDescriptionRuleRuleMatchCategory[] categoryField;
    
    private RulePackRulesRuleDefinitionsCustomDescriptionRuleRuleMatchSubcategory[] subcategoryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Category")]
    public RulePackRulesRuleDefinitionsCustomDescriptionRuleRuleMatchCategory[] Category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Subcategory")]
    public RulePackRulesRuleDefinitionsCustomDescriptionRuleRuleMatchSubcategory[] Subcategory {
        get {
            return this.subcategoryField;
        }
        set {
            this.subcategoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns://www.fortifysoftware.com/schema/rules")]
public partial class RulePackRulesRuleDefinitionsCustomDescriptionRuleRuleMatchCategory {
    
    private string valueField;
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns://www.fortifysoftware.com/schema/rules")]
public partial class RulePackRulesRuleDefinitionsCustomDescriptionRuleRuleMatchSubcategory {
    
    private string valueField;
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns://www.fortifysoftware.com/schema/rules")]
public partial class RulePackRulesRuleDefinitionsCustomDescriptionRuleDescription {
    
    private string abstractField;
    
    private string explanationField;
    
    private string recommendationsField;
    
    private RulePackRulesRuleDefinitionsCustomDescriptionRuleDescriptionContentType[] contentTypeField;
    
    private RulePackRulesRuleDefinitionsCustomDescriptionRuleDescriptionTipsTip[] tipsField;
    
    private RulePackRulesRuleDefinitionsCustomDescriptionRuleDescriptionReferencesReference[] referencesField;
    
    private string formatVersionField;
    
    /// <remarks/>
    public string Abstract {
        get {
            return this.abstractField;
        }
        set {
            this.abstractField = value;
        }
    }
    
    /// <remarks/>
    public string Explanation {
        get {
            return this.explanationField;
        }
        set {
            this.explanationField = value;
        }
    }
    
    /// <remarks/>
    public string Recommendations {
        get {
            return this.recommendationsField;
        }
        set {
            this.recommendationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ContentType")]
    public RulePackRulesRuleDefinitionsCustomDescriptionRuleDescriptionContentType[] ContentType {
        get {
            return this.contentTypeField;
        }
        set {
            this.contentTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Tip", typeof(RulePackRulesRuleDefinitionsCustomDescriptionRuleDescriptionTipsTip))]
    public RulePackRulesRuleDefinitionsCustomDescriptionRuleDescriptionTipsTip[] Tips {
        get {
            return this.tipsField;
        }
        set {
            this.tipsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Reference", typeof(RulePackRulesRuleDefinitionsCustomDescriptionRuleDescriptionReferencesReference), IsNullable=false)]
    public RulePackRulesRuleDefinitionsCustomDescriptionRuleDescriptionReferencesReference[] References {
        get {
            return this.referencesField;
        }
        set {
            this.referencesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string formatVersion {
        get {
            return this.formatVersionField;
        }
        set {
            this.formatVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns://www.fortifysoftware.com/schema/rules")]
public partial class RulePackRulesRuleDefinitionsCustomDescriptionRuleDescriptionContentType {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns://www.fortifysoftware.com/schema/rules")]
public partial class RulePackRulesRuleDefinitionsCustomDescriptionRuleDescriptionTipsTip {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns://www.fortifysoftware.com/schema/rules")]
public partial class RulePackRulesRuleDefinitionsCustomDescriptionRuleDescriptionReferencesReference {
    
    private string titleField;
    
    private string authorField;
    
    private string pagesField;
    
    private string publishedDateField;
    
    private string publisherField;
    
    private string sourceField;
    
    /// <remarks/>
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string Author {
        get {
            return this.authorField;
        }
        set {
            this.authorField = value;
        }
    }
    
    /// <remarks/>
    public string Pages {
        get {
            return this.pagesField;
        }
        set {
            this.pagesField = value;
        }
    }
    
    /// <remarks/>
    public string PublishedDate {
        get {
            return this.publishedDateField;
        }
        set {
            this.publishedDateField = value;
        }
    }
    
    /// <remarks/>
    public string Publisher {
        get {
            return this.publisherField;
        }
        set {
            this.publisherField = value;
        }
    }
    
    /// <remarks/>
    public string Source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns://www.fortifysoftware.com/schema/rules")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="xmlns://www.fortifysoftware.com/schema/rules", IsNullable=false)]
public partial class NewDataSet {
    
    private RulePack[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RulePack")]
    public RulePack[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
